// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");
var CountrySelect$CountrySelect = require("./CountrySelect.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(CountrySelect$CountrySelect.make, {}), "root");

/*  Not a pure module */
